### ISSUE TITLE
Set email per role

### ISSUE THREAD

**Issue by cespare** [philc/watchman#4]
The idea is to have a contacts table with name -> emails (or list of emails?). A role has one or more contacts associated with it.

It may make sense to have a default contact that's filled in for you when you create a new role, as the default.

There are many use cases one could imagine here (e.g., sending business and ops alerts to different email addresses) but one primary use case is to allow a user to test a new alert by sending it to themselves for a while before unleashing it at a wider team.

**Comment by dmac** [comment]
Done in 55f246f3173e4cc389eb392ce55b38c212ea315a.
